version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sigma-mining-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Ensure this matches the password your app is using
    volumes:
      - mining_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5431:5432"

  app:
    image: ghcr.io/marctheshark3/sigmanaut-mining-pool-ui:main
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password  # Ensure this matches the POSTGRES_PASSWORD
      - DATABASE_NAME=sigma-mining-db
    volumes:
      - ./:/app
    ports:
      - "8050:8050"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  mining_data:
