version: '3.8'
services:
  ui:
    image: ghcr.io/marctheshark3/sigmanaut-mining-pool-ui:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/app/conf:ro
      - flask_session:/app/flask_session
    ports:
      - "8050:8050"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1  # Enable real-time logging
      - BASE_URL=${BASE_URL:-http://localhost}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    networks:
      - app_network
    
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 256M
    restart: unless-stopped
    networks:
      - app_network

  miner-id-minter:
    image: ghcr.io/marctheshark3/sigmanaut-mining-pool-minter:${TAG:-latest}
    build:
      context: ./off-chain
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=/miner-id-minter
      - REACT_APP_BASE_URL=${BASE_URL:-http://localhost}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    depends_on:
      - ui
    networks:
      - app_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/nginx.rate.conf:/etc/nginx/conf.d/rate_limit.conf:ro
      - nginx_cache:/var/cache/nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    command: >
      /bin/sh -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf 
      && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    depends_on:
      - ui
      - miner-id-minter
    restart: unless-stopped
    networks:
      - app_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
      - EMAIL_FOR_SSL=${EMAIL_FOR_SSL}
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  nginx_cache:
  flask_session:
  certbot_www:
  certbot_conf: