version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/ssl:/etc/nginx/ssl:ro
      - ./conf/nginx.rate.conf:/etc/nginx/conf.d/rate_limit.conf:ro
      - nginx_cache:/var/cache/nginx
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    depends_on:
      - ui
    restart: unless-stopped
    networks:
      - app_network

volumes:
  nginx_cache: 