version: '3.8'
services:
  ui:
    image: ghcr.io/marctheshark3/sigmanaut-mining-pool-ui:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/app/conf:ro
      - flask_session:/app/flask_session
    ports:
      - "8050:8050"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1  # Enable real-time logging
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    networks:
      - app_network
    
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.20'
          memory: 256M
    restart: unless-stopped
    networks:
      - app_network

  miner-id-minter:
    image: ghcr.io/marctheshark3/sigmanaut-mining-pool-minter:${TAG:-latest}
    build:
      context: ./off-chain
      dockerfile: Dockerfile
    volumes:
      - ./off-chain:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    depends_on:
      - ui
    networks:
      - app_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/ssl:/etc/nginx/ssl:ro
      - ./conf/nginx.rate.conf:/etc/nginx/conf.d/rate_limit.conf:ro
      - nginx_cache:/var/cache/nginx
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    depends_on:
      - ui
      - miner-id-minter
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
  nginx_cache:
  flask_session: